### ISSUE TITLE
Scrape only messages and id

### ISSUE THREAD

**Issue by 3rdxw** [artmih24/TeleParser#1]
Scrape only messages and their id, how I can achieve that?

**Comment by artmih24** [comment]
If you need to scrape only messages and their IDs, you can add all fields except message text and message ID to dictionary on line 149 (which is value of '$unset' field in MongoDB query dict). Example: `'field_name': ''`
If you need, I can add comments in English

**Comment by 3rdxw** [comment]
Thanks, but I need it for the CSV file?
